/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_math_math */

#ifndef _Included_com_example_android_math_math
#define _Included_com_example_android_math_math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_math_math
 * Method:    NativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_math_math_NativeAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_android_math_math
 * Method:    NativeSub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_math_math_NativeSub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
